### ISSUE TITLE
Reactive connected property

### ISSUE THREAD

**Issue by Christilut** [probil/vue-socket.io-extended#117]
Hey, thanks for this plugin. Works great and the upgrade from `vue-socket.io` was much needed.

I've noticed that the `$socket.connected` and `$socket.disconnected`` properties are not reactive. Any way to do this or can I request this feature? :)

Thanks

**Comment by probil** [comment]
Hi, @Christilut and thanks for your issue. :+1: 

`this.$socket.connected` is actually the same as `socket.connected`. I mean, `this.$socket` is just socket.io client instance attached to the Vue. It's not part of the Vue and doesn't use Vue's reactivity system but you have full access to socket.io client and can do everything on it.

But in general it seems like a good suggestion. :thinking: 

Currently I use a `socket` store for that reason.
```js
// src/store/modules/socket.js
export default {
  namespaced: true,
  state: {
    connected: false,
  },
  mutations: {
    SOCKET_CONNECT(state) {
        state.connected = true
    },
    SOCKET_DISCONNECT(state) {
        state.connected = false
    },
  },
}

// src/store/index.js
import Vue from 'vue'
import { Store } from 'vuex'
import socket from './modules/socket.js'

export default new Store({
  modules: {
    socket,
  }.
});

// src/App.vue   ( or any other component )
import { mapState } from 'vuex'
import Vue from 'vue'
import store from './store'

new Vue({
  el: '#app',
  store,
  computed: {
    ...mapState('socket', ['connected']}, // <-- registers `this.connected` which is reactive
    
    onlineIndicatorColor() {
      return this.connected ? 'green' : 'red'; // <-- use `this.connected` as any other reactive prop
    },
  },
})
```

What do you think about that approach? Do you like it or not? 

If you have better ideas I'm open to suggestions :ear: :smile:

**Comment by Christilut** [comment]
I think that works but it seems like its simpler if the $socket.connected (or maybe something else if these properties are directly from the socket) would be reactive. Because in any component you could simply say `v-if="$socket.connected"` without any extra code.

And since it is Vue, I kind of expect plugins to be reactive, that's the great part of Vue! :smile:

**Comment by probil** [comment]
I like the idea and I think we can implement it but with little API change
- `this.$socket` - should be and object with different plugin configuration
- `this.$socket.connected` - reactive property that indicates connection status, allows to write this in template `v-if="$socket.connected"`
- `this.$socket.client` - instance of socket.io client, e.g. to emit an event we need to call it this way `this.$socket.client.emit('MESSAGE', {})` instead of `this.$socket.emit('MESSAGE', {})`

Also, I think it will be useful to expose those fields as well:
- `this.$socket.defaults` - object that contains default plugin options
- `this.$socket.defaults.eventToActionTransformer` - access to default event to action transformer function (useful when you'd like to reuse defaut transformer)
- `this.$socket.defaults.eventToMutationTransformer` - access to default event to action transformer function (useful when you'd like to reuse default transformer)

**Comment by Christilut** [comment]
Sounds perfect :+1:

**Comment by dustingraham** [comment]
I had not heard of this repository. I tried this code with `vue-socket.io` and was stumped that `SOCKET_CONNECT` was not firing. Found out that with `vue-socket.io` it is `SOCKET_connect` and `vue-socket.io-extended` it is `SOCKET_CONNECT`

Stumbled upon here on a google search for `vue-socket.io reactive` (top result), so it may help others if they're confused.

**Comment by probil** [comment]
Implemented in `v4`
