### ISSUE TITLE
question about emit

### ISSUE THREAD

**Issue by kadko** [probil/vue-socket.io-extended#201]
augmentMethod(Socket, 'onevent', (packet) => {
      const [eventName, ...args] = packet.data;
      GlobalEmitter.emit(eventName, ...args);
      passToStore(eventName, args);
    });

Socket.onevent function already have emit call (`emit.apply(...)`) 
Above `augmentMethod` function you call emit again. I confused about this. Can you clarify

**Comment by probil** [comment]
Hi, @kadko 
Nice to see issues from you 👋 

The problem is that there is no way in `socket.io` to listen for all events like this:
```js
socket.on('*', () => {});
```
So we have to replace original method (`Socket.onevent`) with a new method that calls original one + callback function. We have to call original method call to keep existing socket.io listeners working.

The `augmentMethod` uses [monkey patching](http://me.dt.in.th/page/JavaScript-override/) technique ( also called `after` decorator) to add extra behavior to `Socket.onevent`. 

There is a plugin [`socketio-wildcard`](https://github.com/hden/socketio-wildcard) that adds support for `socket.on('*', () => {})` and it uses the [same technique](https://github.com/hden/socketio-wildcard/blob/master/index.js#L8). We don't use this plugin because it's one more dependency and it may conflict if it's used few times.

Let me know if you have any other questions 😺

**Comment by kadko** [comment]
Then all events emitted twice, an same event callback function runs twice isnt it?

**Comment by kadko** [comment]
ok I got it after reading code again

**Comment by probil** [comment]
Nice to see. Feel free to any other questions :)
