### ISSUE TITLE
The sequence of arguments in the server message is broken

### ISSUE THREAD

**Issue by djbaldey** [probil/vue-socket.io-extended#291]
We have a long running great app on Socket.io. And when we decided to move some of our clients to Vue.js faced such a problem.

server:

```js
socket.on('tests.message', function() {
  // No errors:
  socket.emit('tests.message', [1, 2, 3]) 
  socket.emit('tests.message', {a:1})
  socket.emit('tests.message', 'data as string')
  // Send error:
  socket.emit('tests.message', false, 'Error data')
  socket.emit('tests.message', null, 'Error data')
  socket.emit('tests.message', undefined, 'Error data')
})
```

client:

```js
const socketMutations = {
  'socket_tests.message' (state, data, error) {
    if (error) {
      throw new Error(error)
    }
    console.log('work with', data)
  }
...
```
But on reception the sequence of arguments is broken
```
work with  [1, 2, 3]
work with {a: 1}
work with data as string
work with [false, "Error data"]
work with [null, "Error data"]
work with [null, "Error data"]
```
Why spoiled the standard mechanism of Socket.io?

**Comment by probil** [comment]
Hi, @djbaldey 
The sequence of arguments is modified by purpose. 
Since Vuex doesn't support multiple arguments [it's recommended to pass them by array of object](https://github.com/vuejs/vuex/issues/366#issuecomment-251746672)
So library automatically wraps multiple args to array when detected.

If it's important for you I can add possibility to re-define wrapping logic. So you will be able to pass all socket arguments as array, for example.

BTW, thanks for the issue

**Comment by probil** [comment]
Example of possible implementation:
```js
const socket = io('http://socketserver.com:1923');
Vue.use(VueSocketio, socket, { 
  store,
  socketArgsTransformer: (args) => { // <-- `args` here is always array of socket.io arguments (from server)
    return args; // <-- this value is passed to action or mutation
  }
});
```
