### ISSUE TITLE
Problem in IE11 (Not Working)

### ISSUE THREAD

**Issue by wilian746** [probil/vue-socket.io-extended#428]
Hello,

I am need support for **### IE11** but when install show error `Sintaxe Error` in console. The same error is repeated in the example described in the documentation. [CodeSandbox](https://codesandbox.io/s/oxqpm54pnq?fontsize=14&module=%2Fsrc%2FApp.vue)

Image with error --> 
![Capturar](https://user-images.githubusercontent.com/12536670/69049549-ed7cf300-09de-11ea-9c87-e95fd8dbd699.PNG)

**Comment by wilian746** [comment]
@probil you can help me with this issue? my job depends on it :'(

**Comment by probil** [comment]
Hi @wilian746 
Thanks for your issue. I don't think the problem is in `vue-socket.io-extended` itself but in `socket.io` which is using `debug` module under the hood. 

Try to replace
```js
import io from "socket.io-client";
// with
import io from "socket.io-client/dist/socket.io.slim.js"; // slim version may not contain `debug`
```

If it doesn't help, try to build for production and show me an error.

P. S. I'm glad that your job depends on it. You'll be paid for it. But I'm getting nothing of this project.

**Comment by wilian746** [comment]
OHHHHH MY GOD, IT'S WORK !!! **TNKS** :D

**Comment by cfroe** [comment]
Perfect this solution helped me as well, perhaps you could move the help into the general description.
Thx
