### ISSUE TITLE
Error when trying to donate a cup of coffee 

### ISSUE THREAD

**Issue by d3vzer0** [probil/vue-socket.io-extended#476]
Heya!

Thanks for building the socket.io-extended package for Vue :) I'm using Quasar so I was happy to see that the documentation included an out-of-the-box working example using Quasar's boot files concept.  

I was trying to buy you a cup of coffee on Ko-Fi but the payment fails when trying to support your account. Is your ko-fi e-mail address still up to date with paypal? I found the following article: https://help.ko-fi.com/hc/en-us/articles/360006917114-PayPal-error-when-I-try-to-support-someone :)

**Comment by probil** [comment]
Hey @d3vzer0 
I am delighted to hear that you are willing to buy me a cup of coffee 😍 
Thanks for opening the issue. I didn't know that it's not working. I've just checked the email and it seems to be valid. There might be a different issue, thought. Paypal was not officially supported in Ukraine for a lot time. Not it's kinda work. I might need to check the profile, provide my passport, etc

I'll drop you a line when I fix that

**Comment by probil** [comment]
It turned out we still can't receive payments in Ukraine through PayPal 😞 


<img width="518" alt="Screenshot 2020-08-19 at 11 58 54" src="https://user-images.githubusercontent.com/6773202/90614523-6f6ea680-e213-11ea-8c0e-6088b5b6b5da.png">

The same with Stripe... 🙄 

I've registered another account in Austria so I can receive payments. Just tried to pay from the old account and it works fine. 🎉  

Hope you still willing to buy me a cup of coffee :) Anyway it was an important lesson. Thanks @d3vzer0 

I'll reopen the issue if you still experience the issue so keep me posted
