### ISSUE TITLE
Usage with vue-router

### ISSUE THREAD

**Issue by xzaz** [probil/vue-socket.io-extended#493]
Basically it's this bug: https://github.com/MetinSeylan/Vue-Socket.io/issues/153

When you load the page with `this.router.$push()` the `sockets` methods never get invoked.

**Comment by xzaz** [comment]
This project seems dead? 👎

**Comment by probil** [comment]
@xzaz Project is not dead. I'm the only maintainer and I have my own life, full-time job, hobbies and family to carry about. It's really hard to find time for time-consuming unpaid open source work. Try to be a bit more appreciative and understandable.

Speaking about your particular problem, why don't you use store instead? There are a lot of caveats with components because they are not available all the time. I mean they are being rendered conditionally and they are designed to render things and not to deal with connectivity and data manipulation. There is a problem of race condition since component can be rendered after the event happened. There is no way to fix it. Store on the other hand is always available. It was designed for data manipulation and using it make much for sense to me for more advance usage.

It's all about how you architect things.
