### ISSUE TITLE
Events on the client are not received unless the server is restarted

### ISSUE THREAD

**Issue by handhikadj** [probil/vue-socket.io-extended#508]
server.js

```javascript
io.on('connection', (socket) => {
    console.log(`someone with socket ID: ${socket.id} is connected`); // <-- this is logged on the server

    socket.emit('appConnected', 'You are connected through websocket');
    
    // Express.js's post
    app.post('/websocket/image-acquired', (req, res) => {
        console.log(`${req.body.file_image} is emitted`); // <-- this is logged on the server
        io.to(socket.id).emit('socketImageAcquired', req.body.file_image); // <-- dunno why the client can't receive this event
    });
});
```

a Vue component:

```javascript
sockets: {
        appConnected(data) {
            console.log(data);
        },
        socketImageAcquired(data) {
            console.log('Image is created');
            setTimeout(() => {
                this.loadingImage = false;
                this.image = data;
            }, 2000);
        },
    },
```

I need to restart the server in order to `socketImageAcquired()` is triggered T_T

Is it because I have `async mounted()` ?

**Comment by probil** [comment]
I'm curious about this line:
```js
io.to(socket.id).emit('socketImageAcquired', req.body.file_image);
```
Since you have an access to the client's socket, why don't you emit the event the same way as above? E.g.:
```js
socket.emit('socketImageAcquired', req.body.file_image);
```
 According to socket's design, every client has its own socket so the message will be received only by the desired client. `io.to('<client_id>').emit()` basically emits an event inside the room. Not sure when the room for the client id is created so this might be a problem
 
 --- 
 
 BTW, what's the point of having dynamic route registered in express on every connection?
 ```js
 app.post('/websocket/image-acquired', (req, res) => { })
 ```
You'll either have multiple routes registered  (for all user) or overwrite route handler on every socket connection. I'm not completely sure how it works on express side but anyway this approach is wrong by design and won't work the way you expect. If you tell me your use case I would try to find a suggest you a better solution for it

**Comment by handhikadj** [comment]
> "According to socket's design, every client has its own socket so the message will be received only by the desired client."

I didn't know this. thanks for the info

this is what I have on my app:

```
1. There is a Go project which is responsible for generate an image
2. As soon as the image is generated, a callback function runs for which the image is sent through HTTP POST request in some form of string which indicates the image path on the Go project.
3. The express in conjunction with Socket.io is responsible to tell the UI that the given image is ready to be served to UI
```

**Comment by handhikadj** [comment]
okay. solved
