### ISSUE TITLE
Cannot receive socket.to(roomId).emit('xxx', data) from server

### ISSUE THREAD

**Issue by loongmxbt** [probil/vue-socket.io-extended#526]
I've stuck here for several time and hope someone can help.
I've seen some related issues but still can't figure out how.
https://github.com/probil/vue-socket.io-extended/issues/517
https://github.com/probil/vue-socket.io-extended/issues/455

Server
```js
io.on('connection', function(socket) {
    socket.on('join', async({ userId, roomId }) => {
      try {
        socket.join(`${roomId}`)
        socket.to(`${roomId}`).emit('roomInfo', {
          action: 'join',
          roomname: roomname,
          username: username,
          roomusers: roomusers
        });
        socket.to(`${roomId}`).emit('message', {
          msg: `User ${username} Joined room ${roomname}`
        })
        socket.emit('test', {
          msg: 'test message'
        })
```

Client Vuex
```js
socket_roomInfo ({ dispatch, commit }, data) {
      console.log('socket roomInfo')
      console.log(data)
    },
    socket_message({ dispatch, commit }, data) {
      console.log('socket message')
      console.log(data)
    },
    socket_test({ dispatch, commit }, data) {
      console.log('socket test')
      console.log(data)
    }
```

Only `socket_test` can receive data, `socket_roomInfo` and `socket_message` cannot receive data.
When I modify server `socket.to(`${roomId}`).emit('roomInfo')` into `socket.emit('roomInfo')`, then I can receive data on client.

So my question is, how can I receive `roomInfo` event data on client vuex?

**Comment by probil** [comment]
Hey @loongmxbt 👋 

Rooms are supported but there is a difference how you use it on the BE. The syntax you use in Vuex actions is correct. 

But according [to the docs](https://socket.io/docs/v2/rooms/), you need to trigger events on `io` (not on `socket`) in order to send message to all room participant:

<img width="982" alt="Screenshot 2021-04-22 at 16 08 43" src="https://user-images.githubusercontent.com/6773202/115719798-1ac49200-a385-11eb-8751-87f13b5aaf36.png">


```js

// sends message to all room member
io.to(roomId).emit('roomInfo', {
  action: 'join'
});

// sends message to all room members excluding the current client
// that's why you don't receive it (!)
socket.to(roomId).emit('roomInfo', {
  action: 'join'
});        
```

Could you confirm that it solves your problem?

**Comment by loongmxbt** [comment]
Thank you very much! Changing `socket.to` into `io.to` solves the problem! I need to watch the docs more carefully.
