### ISSUE TITLE
How to receive/emit to a particular user? 

### ISSUE THREAD

**Issue by harishankards** [probil/vue-socket.io-extended#71]
Hi @probil,

Hope you are doing good. Now, I have a use case for having a pushing notification to the particular user and also in future I might implement chat system.

In that case, I would have to emit/receive data to a particular user right. How would I achieve it with the package? If you could throw me some docs or examples, would be useful.

**Comment by probil** [comment]
Basically, it's not the client library job to deliver data to the particular user. The server should do that. All clients connected to socket.io have unique ids so the server could identify them.
There is also a method on the server that allows sending events directly to the connected user by his id. Simplified flow:

=> client emits event  (e.g. `{ message: 'Hi there', forUser: 15 }`)
=> server validates event and looking for socket id (e.g. `haxf0EcykhJ6`) by user id (e.g. `15`)
=> server delivers a message to end user (using the id, e.g. `haxf0EcykhJ6`)
=> end user accepts message using `vue-socket.io-extended` listener
Also, it's possible to use rooms but it's more advanced topic.

I'm sure there are tons of info on the internet about this topic. Try " chat socket.io".  The only difference is on the front-end but it's minor and easy understand how to port existing article examples to `vue-socket.io-extended`

If you have any troubles - let me know :)

**Comment by probil** [comment]
I have to close your question because it's not actully issue or bug or feature request. It's not even directly related to `vue-socket.io-extended`.
Let's continue discussion in [gitter chat](https://gitter.im/vue-socket-io-extended/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link).
Please create new issue if you have any other questions :) I will be glad to help you :handshake:
