### ISSUE TITLE
ESLint requires Vuex actions to be "camelcased"

### ISSUE THREAD

**Issue by etcogit** [probil/vue-socket.io-extended#89]
Hi,

I use EsLint to lint my code. EsLint requires actions to be "camelcased" but vue-socket.io(-extend) does not respect this requirement... How could I fix that?
SERVER:
```javascript
socket.emit('myTestSocket', 'this is a test socket')
```
ACTIONS:
```javascript
actions: {
  socket_myTestSocket (values) { // -> error: should be socketMyTestSocket ?
    console.log('this is the response of the server: ' + values)
  }
}
```

**Comment by probil** [comment]
Hi, @etcogit. Thanks for your issue. :+1: 
There are at least two ways how it can be achieved:
1) **Configure eslint to ignore `socket_` prefixes.**

I don't know what rules or code style guide you are using so I can't provide you eslint config right now. But you can try to investigate eslint docs by yourself. There should be an ability to add exceptions to the rule. Or provide me eslint log & config and I will try to help you somehow.

2) **Configure `vue-socket.io-extended` to use you naming convention.**
Pass custom action prefix `socket` instead of default `socket_`. For example:
```diff
- Vue.use(VueSocketio, io('http://socketserver.com:1923'), { store });
+ Vue.use(VueSocketio, io('http://socketserver.com:1923'), { 
+   store,
+   actionPrefix: 'socket',
+ });
```
But in this case your action will look like `socketmyTestSocket`, probably you have to pass event to action transformer as well, to make it trully camelcased:
```js
import PascalCase from 'pascal-case'

Vue.use(VueSocketio, io('http://socketserver.com:1923'), { 
  store,
  actionPrefix: 'socket',
  eventToActionTransformer: PascalCase, // <-- custom transformer
});
```
After that you can write actions as desired -> `socketMyTestSocket`.

**Comment by etcogit** [comment]
Hi,

Thanks for reply.
I searched EsLint doc to reach your first solution but didn't find. Instead I saw we can "disable" a linting rule on a portion of code like this:
```
/* eslint-disable camelcase */
// Here is the code I don't want to be checked for camlecase rule
actions: {
  socket_myTestSocket (values) { // -> error: should be socketMyTestSocket ?
    console.log('this is the response of the server: ' + values)
  }
}
/* eslint-enable camelcase */
```
It worked perfectly.
So I didn't try the second way you proposed.

Thanks a lot

**Comment by probil** [comment]
Great, @etcogit . I consider the issue as solved and close. Let me know if you have any other issues. I will be glad to help :handshake: 
Have a nice day :)
